#-------------------------------
# General Site Settings
title: "Sean's Data Blog"
description: "Sean's Notes on Data"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seandavidthompson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: "Sean David Thompson"

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  style: compressed
